### ISSUE TITLE
Carpet for Skyblock.6 crashes when opening Single Player screen

### ISSUE THREAD

**Issue by Kinomora** [DeadlyMC/QuickCarpet114#10]
Info:
MC 1.14.0
Fabric: 1.14+build.7-0.4.5+build.141
API: fabric-0.2.6.121
quickcarpet114-1.8.0

Game loads fine, mod causes a mouseclickevent crash when clicking the "Single Player" menu option on the loading screen. Disabling carpet mod prevents the crash. Can click "Multiplayer" without crashing with mod enabled.

Crash Report: https://pastebin.com/RdtyWp4j

**Comment by DeadlyMC** [comment]
Looks like you have the Fabric API for snapshot-**19w14b**. You gotta update to [1.14 API](https://minecraft.curseforge.com/projects/fabric/files/2702281)

**Comment by Riverstarship** [comment]
Also experiencing this issue using the 1.14 API, same error. The game crashes upon attempting to load the singleplayer menu with worlds, and upon attempting to generate a new world. It does not crash when loading the multiplayer menu or when loading the singleplayer menu without worlds. Joining a server provides the same error message but does not crash:
"org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered"

**Comment by MGlolenstine** [comment]
I can confirm that the abovementioned problem persists in 1.14 API

**Comment by MGlolenstine** [comment]
@Riverstarship  and @Kinomora you can use second to last version for the time being... https://github.com/DeadlyMC/QuickCarpet114/releases/tag/1.8.0%2Bskyblock.6 it works fine for me.

**Comment by skyrising** [comment]
@Kinomora The crash log says you have 1.8.0 (which has a crash bug), not 1.8.0+skyblock.6 (which should work fine).
Either use 1.8.1 or 1.8.0+skyblock.6

**Comment by Kinomora** [comment]
Yes, I can confirm I am dumb and somehow managed to download the wrong mod :'D
SB.6 works on the latest API build.
Thanks for the help :)
