### ISSUE TITLE
skyblock rain is hitting blocks that are not there

### ISSUE THREAD

**Issue by SpeedRider** [DeadlyMC/QuickCarpet114#11]
when it rains the rain thinks theirs blocks there i'm guessing it's using the seed to work out were the blocks are rather then testing if theirs blocks there or it's the world not have the blocks that are meant to be there that's making it act funny.
i believe if you place a block and brake it it up dates as long as you are above the blocks that the rain is hit that's not there. 
i'm using the same seed as sicraft skyblock.

![2019-05-03_20 24 06](https://user-images.githubusercontent.com/17522328/57137275-f52dcf00-6de1-11e9-9ff4-7c271e2f6d05.png)
![2019-05-03_20 24 01](https://user-images.githubusercontent.com/17522328/57137277-f52dcf00-6de1-11e9-9b91-e9970ec6745c.png)
![2019-05-03_20 24 03](https://user-images.githubusercontent.com/17522328/57137279-f52dcf00-6de1-11e9-886f-63f5fd9210c7.png)

i did leave those cauldrons there long enough to have at least 1 of them filled.

**Comment by skyrising** [comment]
Are you using the world download or just the same seed?
Which version of Quick Carpet are you using?

**Comment by skyrising** [comment]
Ok, this should have been fixed in dd7000b but apparently wasn't.
Can reproduce it.

**Comment by skyrising** [comment]
Fixed in d841384

**Comment by SpeedRider** [comment]
sorry i did not get any msgs

**Comment by SpeedRider** [comment]
should i update
