### ISSUE TITLE
What do I use for generator setting while setting up a server

### ISSUE THREAD

**Issue by MadCow667** [DeadlyMC/QuickCarpet114#13]
I was setting up a server and didn't know what to put in for generator settings in [server.properties](https://server.properties)

**Comment by NicklasE99** [comment]
Use the world file from ilmango's video and you can leave the generator settings empty.

**Comment by DeadlyMC** [comment]
I finally got time to test this :P
You shouldn't change generator-settings. U just need to change the level-type to skyblock (**level-type=skyblock**) and run it like any other server
