### ISSUE TITLE
Skyblock custom generation not work

### ISSUE THREAD

**Issue by N4TH4NOT** [DeadlyMC/QuickCarpet114#14]
On the latest version I can't use the custom generation but with the same configuration with version 1.7.1, skyblock custom generation work...
It was normal ??

Thanks for potential answer :3
N4TH4NOT

####################
Minecraft informations
####################

Version : Release 1.14
Fabric loader : 0.4.7-build.147
Fabric API : 0.2.7-build.127
Mod version : 1.9.2

**Comment by Nachtalb** [comment]
I think you use the wrong version of the mod. 

> Mod version: 1.9.2

`1.9.2` is not out with skyblock yet

You have to use the skyblock version of the mod (based on `1.9.1` ATM) https://github.com/DeadlyMC/QuickCarpet114/releases/tag/1.9.1%2Bskyblock.6

**Comment by DeadlyMC** [comment]
Yup...as @Nachtalb told 1.9.2 is not for skyblock...only particular releases are for skyblock

**Comment by N4TH4NOT** [comment]
Yes that work !

Thaks and sorry for this useless issue ^^'
