### ISSUE TITLE
Bug while dying Shulker Boxes

### ISSUE THREAD

**Issue by aRandomPerson1** [DeadlyMC/QuickCarpet114#15]
It isn't possible to dye a Shulkerbox on a crafting table while autoCraftingTable is activated. Is that a bug?

**Comment by InvalidString125** [comment]
It seems like you can't craft anything that has NBT data in the Output

**Comment by Marlonzockt** [comment]
Have a look at that issue: https://github.com/DeadlyMC/QuickCarpet114/issues/23
