### ISSUE TITLE
QuickCarpet without Skyblock does not allow Fabric clients without the mod to connect.

### ISSUE THREAD

**Issue by chexo3** [DeadlyMC/QuickCarpet114#17]
I think it's because it registers carpet:crafting_table, which  I assume is an optimized crafting table. I don't need that, can I disable it somehow?

**Comment by skyrising** [comment]
Is there an error message (or crash log)?

**Comment by skyrising** [comment]
carpet:crafting_table is the block entity for the automatic crafting table.
I don't think it's at fault here. More likely a problem with the command tree. I'm getting a DecoderException/IndexOutOfBoundsException when I'm opped (that's when the carpet command tree is sent to the client). Can you confirm this?
Which version are you using?

**Comment by DeadlyMC** [comment]
@chexo3 could u try out the new Quickcarpet release for 1.14.2 and confirm if it works?

**Comment by Schachmatt11** [comment]
It's still does not work for me with the new 1.14.2 release

**Comment by fxmorin** [comment]
Yup this is still an issue. Just got the error. Although mine tells me it's because the super_potions are missing

**Comment by bloodymaestro** [comment]
Quickcarpet straight up doesnt work
There is no option for skyblock generation and any old skyblock generated world reverts to normal world generation

**Comment by Cynosphere** [comment]
Only occurs if the server has Fabric API installed and the client has it too. Unless you have extra mods that need Fabric API on the server, you don't need it to run QuickCarpet at all.

Otherwise you just have to tell people with Fabric API on their client to add QuickCarpet to their mods folder.
