### ISSUE TITLE
The end portal in the end generate error.

### ISSUE THREAD

**Issue by Ling-Jing** [DeadlyMC/QuickCarpet114#18]
The end portal is generated a part at y=0. I've tried all 1.14-1.14.2 version that have the same problem. There is the shortcut
![image](https://user-images.githubusercontent.com/48620702/58784398-e1aa9980-8615-11e9-977f-80bdecbd96d7.png)

**Comment by skyrising** [comment]
This is a vanilla bug: https://bugs.mojang.com/browse/MC-93185

**Comment by skyrising** [comment]
This is fixed in the next release. `endPortalFix` rule will be enabled by default
