### ISSUE TITLE
1.14.3 pre1 not opening

### ISSUE THREAD

**Issue by homeless-samurai** [DeadlyMC/QuickCarpet114#22]
when starting minecraft in 1.14.3 with the fabric profile, im getting the message "it looks like you are running an unsupported modified version of the game" and the game stops. 
this only happens with the quikcarpet mod in the mods folder, any other mod works fine.

using newest quikcarpet and fabric. tried it with and without the skyblock, but still doesnt work.

**Comment by DeadlyMC** [comment]
There are no releases for 1.14.3 pre-releases out yet
