### ISSUE TITLE
Better Potions

### ISSUE THREAD

**Issue by That1Clarinet** [DeadlyMC/QuickCarpet114#25]
I may be missing a setup command somewhere but i cant seem to find one. Better potions is just not working. I cant even put the redstone block in the brewing stand.

**Comment by DeadlyMC** [comment]
You need the quickcarpet jar packed with skyblock module...can u show me ur mods folder

**Comment by That1Clarinet** [comment]
Its just quickcarpet114-1.12.1+build.2.jar

**Comment by DeadlyMC** [comment]
You r using the wrong version..it needs to be **quickcarpet114+skyblock.1.1.0-1.12.1+build.2.jar** (Current latest)

**Comment by That1Clarinet** [comment]
Thank you so much!
