### ISSUE TITLE
Cant get features to work

### ISSUE THREAD

**Issue by nng900** [DeadlyMC/QuickCarpet114#32]
I followed Ilmangos video, and I know the mod is loaded, because when I look at a block f3 says "#carpet dispenser_placeable_whitelist" or something like that, but none of the features of quick carpet are working. not dispensers placing blocks, not the cobble to sand via anvil thing, not the movable tile entities. I have tried several different versions on MC, QuickCarpet, and Fabric, but nothing works. Oh, and the skyblock mod worked fine.

**Comment by bnjw5jhyxn** [comment]
The features you list are turned off by default. Have you entered commands like `/carpet dispensersPlaceBlocks all`? Additionally, to make the settings persistent across login sessions, use `/carpet setDefault dispensersPlaceBlocks all`. You can see all settings with `/carpet list`.

**Comment by nng900** [comment]
I had no idea! Thank you! Is there a list of all the commands to enable these features?

**Comment by nng900** [comment]
Thanks so much!
