### ISSUE TITLE
NoSuchMethodError on server

### ISSUE THREAD

**Issue by 1a2s3d4f1** [DeadlyMC/QuickCarpet114#34]
The server crashed while used /tick freeze
Fabric API 0.3.0 + build.207
MC 1.14.4
Fabric Loader 0.4.8 + build.159
yarn:1.14.4+build.9
Crash Report : https://paste.ubuntu.com/p/MZ32fmk5NM/

**Comment by skyrising** [comment]
Can you try deleting the .fabric directory and see if the problem persists?

**Comment by 1a2s3d4f1** [comment]
The problem persists when I delet .fabric directory
https://paste.ubuntu.com/p/B7vnp2g3yq/

**Comment by skyrising** [comment]
This issue seems to have come up again (#44). Did you find a solution to get it to work?

**Comment by skyrising** [comment]
At the moment 1.14.4 is unsupported. I'll try to release a stable version for 1.14.4, but updating to 1.15.1 is recommended.
