### ISSUE TITLE
Port renewable sponge feature from Carpet mod.

### ISSUE THREAD

**Issue by AhramanOld** [DeadlyMC/QuickCarpet114#35]
This has two benefits; the obvious one is renewable sponge, which is mostly useless considering the world is completely void, but may still become handy. The other is that as far as I am aware, there is no other way of getting the Mining Fatigue debuff, making one of the advancements impossible to achieve in a SkyBlock world.

**Comment by skyrising** [comment]
Added with 2e87f37c644f072b697b9e5be96b4b980cfd0e0d
