### ISSUE TITLE
Auto Crafting Tables Can Pushed Even When Movable Tile Entities Are Disabled

### ISSUE THREAD

**Issue by SharpNeutrons** [DeadlyMC/QuickCarpet114#38]
If auto crafting tables are enabled (using the "/carpet autoCraftingTable true" command) and movable tile entities are disabled (either through the default behavior, or by using the "/carpet movableBlockEntities false" command) the crafting table tile entities can still be moved by pistons.
When the crafting tables are moved under these circumstances, their inventories are thrown on to the ground.

**Comment by skyrising** [comment]
This is fully intended, as the normal crafting table is also movable.
