### ISSUE TITLE
Pre-release v2.0.0-dev causes RuntimeExcpetion when starting server

### ISSUE THREAD

**Issue by siiikooo0743** [DeadlyMC/QuickCarpet114#39]
When i start the fabric server with the pre-release v2.0.0-dev quick carpet mod, the server crashes with a RuntimException.
I'm on linux (NixOs). My java version:

    $ java --version
    openjdk 11.0.3-internal 2019-04-16
    OpenJDK Runtime Environment (build 11.0.3-internal+0-adhoc..jdk11u-jdk-11.0.3-ga)
    OpenJDK 64-Bit Server VM (build 11.0.3-internal+0-adhoc..jdk11u-jdk-11.0.3-ga, mixed mode)

I was using the fabric installer for servers with java version 1.14.4 and tried the two newest versions of fabric (0.6.0 build 163 and 0.6.1 buidl 164) both causing the same error. 
Without the mod both versions started without any problem.
QuickCarpet v1.13.0 runs fine with minecraft 1.14.3.

The output of the server is attached (slight modifictaions for privacy reasons):
[output.txt](https://github.com/DeadlyMC/QuickCarpet114/files/3562565/output.txt)

Is there any piece of information you need, that i forgot?
Can I help by somehow running in debug mode or something?

**Comment by skyrising** [comment]
This is caused by a bug in the Mixin library that is used to modify Minecraft's behavior, which manifests in Java 9+. It'll be fixed in the next release. The workaround is to use Java 8.
