### ISSUE TITLE
Can't get a wandering trader to spawn.

### ISSUE THREAD

**Issue by Jubber4442** [DeadlyMC/QuickCarpet114#45]
I downloaded the skyblock world download. And we stood afk for well above 10 real time hours. No wandering trader appeared. Do you know why? I tried tick warping in a random generated world, and a wandering trader appeared, then i tried testing a copy of the world download, and no wandering trader seems to be spawning.

Thank you in advance.

Jubber

**Comment by skyrising** [comment]
Wandering traders have very special spawning conditions, making them very rare in skyblock. You will need to prepare a large platform with the right conditions.
QuickCarpet doesn't change the way wandering traders spawn.
