### ISSUE TITLE
Moving a crafting table doesn't close its inventory

### ISSUE THREAD

**Issue by karlkoorna** [DeadlyMC/QuickCarpet114#47]
### Environment
* Minecraft 1.14.4
* Carpet 2.0.0-dev

### Current behavior
When a crafting table is moved by a piston the opened inventory does not close.

Demonstration of broken behavior with `autoCraftingTable` enabled:
https://streamable.com/0tqc9

### Expected behavior
The inventory closing on move like in vanilla.

Demonstration of vanilla behavior with `autoCraftingTable` disabled:
https://streamable.com/opguw

**Comment by skyrising** [comment]
I don't see how that is an issue. As long as nothing is broken because of that behavior I think it's nice to be able to look into what's happening in a crafting table even while it's moving around.
