### ISSUE TITLE
Wander Skyblock Trades not working

### ISSUE THREAD

**Issue by danielrello** [DeadlyMC/QuickCarpet114#53]

**Comment by DeadlyMC** [comment]
Please describe your issue. Just simply having a title doesn't really help. 
My first assumption is that you don't have the skyblock extension mod

**Comment by danielrello** [comment]
Hi, I've been looking the source files and I found that the last version (1.15.2 compatible) doesn't have the Skyblock files, I tried to add them manually an build it but didn't work... Any ideas?

El 6 mar. 2020 8:22, DeadlyMC <notifications@github.com> escribió:

Please describe your issue. Just simply having a title doesn't really help.
My first assumption is that you don't have the skyblock extension mod

**Comment by DeadlyMC** [comment]
You get the skyblock mod from here :
https://github.com/skyrising/skyblock

**Comment by DeadlyMC** [comment]
Make sure you get the correct one as per your requirement. The one with `-fc` suffix is for fabric-carpet and not quickcarpet

**Comment by danielrello** [comment]
Thank you very much!
