### ISSUE TITLE
Some areas lit up by itself without light source

### ISSUE THREAD

**Issue by gabultimate** [DeadlyMC/QuickCarpet114#56]
Some of the blocks are lit up by itself. I copied part of the world from my previous skyblock server because I was not using the right skyblock quick carpet generation mod. I created another new world with the right world generation mods and pasted my previous part of the world using worldedit. How do I remove these spontaneous lit up blocks?

**Comment by gabultimate** [comment]
It doesnt just happen to previously pasted blocks, it happens to new unexplored areas which I didn't copy from the old world and where I placed blocks.

**Comment by gabultimate** [comment]
I assume its because I'm building in an ocean variant biome at lower levels, there were sea pickles there before the skyblock world generation removed them, but the light source remains there, so there are patches of light in some area without any current light supplied to them. Or I could be totally wrong.

**Comment by JeremiahK96** [comment]
I have seen this, as well. I built a staircase down to Y0, and platformed out with planks from there, so I can just build upwards wherever I need to.  There are random patches of planks that are lit up.
My theory is that they are lava lakes from the world generation, that somehow even though the lava isn't present, the light still is.

**Comment by JeremiahK96** [comment]
This is not in an ocean biome btw, plains, forest, and mountain

**Comment by Ghoulboy78** [comment]
https://www.youtube.com/watch?v=JtoTAkjpuHA

**Comment by Ghoulboy78** [comment]
It is possible for it to happen by accident as well

**Comment by skyrising** [comment]
QuickCarpet and SkyBlock were split up a while ago and the issue should be fixed by now. If it still exists in the current version of SkyBlock please report it again at https://github.com/skyrising/skyblock/issues
