### ISSUE TITLE
Updating to 1.16?

### ISSUE THREAD

**Issue by vojtamares** [DeadlyMC/QuickCarpet114#58]
Hello,

I was wondering if you are planning on updating quickcarpet to 1.16, since I use QuickCarpet instead of FabricCarpet due to MiniHUD mod server-side compatibility. Will you update QuickCarpet to MC1.16?
Thanks

**Comment by skyrising** [comment]
Yes, there are branches for a few snapshots and prereleases, including 1.16-rc1, so assuming 1.16 doesn't change anything compared to rc1 it's ready to be released at the same time
