### ISSUE TITLE
Can't download .jar file

### ISSUE THREAD

**Issue by DynamicDude2** [DeadlyMC/QuickCarpet114#74]
I downloaded .zip file and converted it to .jar but it is not working. What version is the mod?

**Comment by skyrising** [comment]
Where did you download this zip file? You probably downloaded the source code.

**Comment by DynamicDude2** [comment]
In the code tab, I went to "code" option next to "add file" then I clicked "HTTPS", "SSH" and "GitHub Cl" and downloaded from all three it says "Download ZIP"

**Comment by skyrising** [comment]
You downloaded the source code. You can get releases either from https://github.com/DeadlyMC/QuickCarpet114/releases or https://github.com/DeadlyMC/QuickCarpet114/actions (download quickcarpet-jars, unzip it and use the one without -dev or -sources)

**Comment by DynamicDude2** [comment]
thanks!
