### ISSUE TITLE
1.16.4 Movable Block Entities breaks pistons

### ISSUE THREAD

**Issue by Nomenator** [DeadlyMC/QuickCarpet114#78]
When I use /carpet movableBlockEntities true in 1.16.4, pistons do not fully retract, can't be mined, and can only be removed when using flexible block placement to force place a block in its place and then mine it. The piston is then lost. Until then, the place where piston was placed becomes unusable.

**Comment by skyrising** [comment]
Which version of QuickCarpet are you using?

**Comment by Nomenator** [comment]
@skyrising 
https://github.com/DeadlyMC/QuickCarpet114/actions/runs/372107407

**Comment by skyrising** [comment]
Please try a newer version, The next commit just after the 1.16.4 update fixed the typo that is probably causing this.

**Comment by Nomenator** [comment]
Yep. This one: https://github.com/DeadlyMC/QuickCarpet114/actions/runs/373006268 totally fixed this.
