### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by bulletwingsga** [DeadlyMC/QuickCarpet114#79]
whenever I try to open game with this mod, the game just crash and do not open. it's fine with other mods, just this one. I'm using 1.16.4 and using 2.4.0 ver of this mod and 1.0.0 api

**Comment by skyrising** [comment]
2.4.0 does not work with 1.16.4, you can get a pre-release version of 3.0.0 at https://github.com/DeadlyMC/QuickCarpet114/releases/tag/v3.0.0-dev-1.16
